### PR TITLE
removed Top and Loc constructors from index_z

### PR DESCRIPTION
**Pull request by domsj**
makes it more logical for me :-)

### CODE REVIEW

**Comment by NicolasT** [comment]
Huh, why would you want to do this?

**Comment by domsj** [comment]
Top (_, t) is actually just the special case Loc (_, [], t); with that last one being an illegal value for Loc (there's several checks on that in the code).
So the split up of the index_z type is 1) unnecessary and 2) creates extra code (this commit removes more code than it adds) and 3) allows for the construction of invalid values (as the types are defined in a too loose way).
So because of these reasons I thought it would be better to remove the separate Top and Loc constructors.

**Comment by NicolasT** [comment]
Hmh, not convinced, since now the type being used is just an alias for some random tuple, not a fresh type.

I'd rather fix the _Loc_ constructor to remove the ability to construct invalid values. 2 approaches (code is OTOH): a hackish one

``` ocaml
type index_z =
  | Top of index
  | Loc of ((pos * kp * (kp list)) * (kp list))
```

or similar but more structured:

``` ocaml
type 'a non_empty_list = Cons of ('a * 'a non_empty_list) | Single of 'a

type index_z =
  | Top of index
  | Loc of ((pos * (kp non_empty_list)) * (kp list))
```

Defining the required/used operations over _non_empty_list_ is trivial.

One more approach, by using a _smart constructor_ (which introduces a runtime check, unlike the above solutions):

``` ocaml
module NonEmptyList = (struct
  type 'a t = 'a list

  let from_list = function
    | [] -> None
    | xs -> Some xs

  let to_list xs = xs
end : sig
  type 'a t
  val from_list : 'a list -> 'a t
  val to_list : 'a t -> 'a list
end)

type index_z =
  | Top of index
  | Loc of ((pos * (kp NonEmptyList.t)) * (kp list))
```

Finally, using GADTs and Peano-numbers, you could implement a list whose length is tracked at compile-time, then encode whether or not a list should be of some minimal length in a type (this rules out using some list operations like _filter_ though). IMHO this might be the best solution, but de gustibus...

**Comment by domsj** [comment]
Ok, non empty list types are rather easy to create.

But honestly, I don't want them, because I don't see the point in separating Loc and Top. Even worse, this artificial distinction creates a need for extra code and it doesn't make anything clearer at all.

You are correct in that the type is just an alias for a tuple, but that could also be easily solved with
type index_z = Indez_z of pos \* (kp list) \* (kp list)

I fully support that remark btw. The same argument however could easily be made about a lot of the types in Baardskeerder.
So imo those other types (I have to look em up, off the top of my head there's also index, leaf and leaf_z) should be changed then as well...
And maybe we should just never use type aliases?

(On a side note: I really have to do some reading about GADTs :-).)

**Comment by NicolasT** [comment]
I'm all in favor of tagged types instead of tuple aliases :wink:

Regarding GADTs to encode type-level length-tracked lists, I thought a demo could be instructive: https://gist.github.com/NicolasT/5373649

**Comment by toolslive** [comment]
Some remarks:
- For me, 'zipper' is a design pattern, which comes in all kinds of flavours. 
- in this codebase, Top & Loc value constructor were named in analogy with Huet's paper.
- The current pull request is indeed a (slightly) tighter formulation for the datastructure we need.
- If you want to do away with coding zippers altogether, you can use metaprogramming to generate them automatically. ( see https://github.com/jaked/cufp-metaprogramming-tutorial/tree/master/exercises/ocaml/zipper )

currently, I'm inclined to merge it in.

**Pull request merged**
